### ISSUE TITLE
Any way to add an aspect ratio field to the catalogue? 

### ISSUE THREAD

**Issue by iloveicedgreentea** [3ll3d00d/beqcatalogue#10]
For context I make this tool https://github.com/iloveicedgreentea/plex-webhook-automation

Part of it is aspect ratio detection. Right now I am using IMDB which is slow and unreliable. If there was a way to add this field to the beq catalogue it would be really helpful. I know its not in the scope of "beq" but it would help me out a lot as there is no other repository (other than imdb) for this data. I use the beqcatalogue already so it would be really convenient. No worries if you don't want to though.

**Comment by 3ll3d00d** [comment]
I looked into a source for this data a while ago & the only thing I found that seemed reliable was https://www.blu-ray.com/

unfortunately, as far as I could tell, they don't have an api so tricky to get hold of the data

if you have any idea of a way to get this data then happy to add it otherwise seems not feasible

**Comment by iloveicedgreentea** [comment]
I have been using IMDB and found it to be mostly accurate. I think a some of it would need to be user submitted or updated, like when people add new BEQ things, but I found IMDB to be fairly reliable. They do list multiple aspect ratios so it depends, and I think its reasonable to include them all because certain formats have different ratios, but that also depends on the release. Some blurays are 2.39 for home media but IMAX in the cinema, some get the IMAX release

If you think blu-ray.com is reliable and are open to adding the field, I am more than happy to write a scraper to get aspect ratio for every movie in the beqcatalog, maybe in a json mapping or whatever you prefer

**Comment by 3ll3d00d** [comment]
I don't mind which source, whatever works and can be accessed easily. Ideally I would pull that scraping into beqcatalogue itself to augment the published metadata without requiring each other to do it.
