### ISSUE TITLE
Show date of media in search results e.g. Road House (2024)

### ISSUE THREAD

**Issue by astubbs** [3ll3d00d/beqcatalogue#11]
Would be great to see the release year of the search result items in the results list when typing.

Use case: distinguish between titles of the same name, released in different years.

Workaround: right click on all search results, open in new tab, inspect the release date for each result in each tab.

I'll try to take a look at how to do this myself soon. I had a look and I think this is the correct repo for this type of issue. Sorry if I got it wrong.

**Comment by 3ll3d00d** [comment]
search is implemented by https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/

it's a pure text search rather than a catalogue search so I'm not sure it's possible to implement this, happy to be proven wrong though
